In [30]:
#Será usado numpy
#Tutorial: https://towardsdatascience.com/top-10-matrix-operations-in-numpy-with-examples-d761448cb7a8

# Inner Product

In [4]:
import numpy as np

In [5]:
a = np.array([1,2,3])
b = np.array([5,-3,8])

In [6]:
print("a = ", a)
print("b = ", b)

a =  [1 2 3]
b =  [ 5 -3  8]


In [10]:
print("\ninner: ", np.inner(a,b))


inner:  23


In [12]:
print("\ndot:  ", np.dot(a,b))


dot:   23


# Objeto: ndarray

In [25]:
a = np.array([[1,3],[2, 0]])
b = np.array([[-2,5,0],[-2,1, -1]])
print("a: ", type(a))
print(a)
print("\nb: ", type(b))
print(b)

a:  <class 'numpy.ndarray'>
[[1 3]
 [2 0]]

b:  <class 'numpy.ndarray'>
[[-2  5  0]
 [-2  1 -1]]


# Objeto: matrix

In [26]:
c = np.matrix([[1,3],[2, 0]])
d = np.matrix([[-2,5,0],[-2,1,6]])
print("\nc: ", type(c))
print(c)
print("\nd: ", type(d))
print(d)


c:  <class 'numpy.matrix'>
[[1 3]
 [2 0]]

d:  <class 'numpy.matrix'>
[[-2  5  0]
 [-2  1  6]]


In [36]:
print("\ninner: ", np.inner(c,d))

ValueError: shapes (2,2) and (3,2) not aligned: 2 (dim 1) != 3 (dim 0)

In [28]:
print("\ninner: ", np.dot(c,d))


inner:  [[-8  8 18]
 [-4 10  0]]


In [33]:
print(a * b)

ValueError: operands could not be broadcast together with shapes (2,2) (2,3) 

# Dot Product

In [34]:
# Matrices as ndarray objects
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [8, 9]])
print("a", type(a))
print(a)
print("\nb", type(b))
print(b)

print("\n* operation on two ndarray objects (Elementwise)")
print("Producto Normal: ", a * b)
print("\n* operation on two matrix objects (same as np.dot())")
print("\nProducto punto: ", np.dot(a,b))

a <class 'numpy.ndarray'>
[[1 2]
 [3 4]]

b <class 'numpy.ndarray'>
[[5 6]
 [8 9]]

* operation on two ndarray objects (Elementwise)
Producto Normal:  [[ 5 12]
 [24 36]]

* operation on two matrix objects (same as np.dot())

Producto punto:  [[21 24]
 [47 54]]


# Transpuesta

In [37]:
a = np.array([[1, 2], [3, 4], [5, 6]])
print("a = ")
print(a)

print("\nWith np.transpose(a) function")
print(np.transpose(a))

print("\nWith ndarray.transpose() method")
print(a.transpose())

print("\nWith ndarray.T short form")
print(a.T)

a = 
[[1 2]
 [3 4]
 [5 6]]

With np.transpose(a) function
[[1 3 5]
 [2 4 6]]

With ndarray.transpose() method
[[1 3 5]
 [2 4 6]]

With ndarray.T short form
[[1 3 5]
 [2 4 6]]


In [38]:
#Transpuesta de un vector: CUIDADO !

In [40]:
a = np.array([1, 2, 3])
print("a = ")
print(a)
print("\nTranspuesta = ")
print(np.transpose(a))

a = 
[1 2 3]

Transpuesta = 
[1 2 3]


In [41]:
#Se debe colocar el vector como un arreglo de dos dimensiones

In [42]:
a = np.array([[1, 2, 3]])
print("a = ")
print(a)
print(np.transpose(a))

a = 
[[1 2 3]]
[[1]
 [2]
 [3]]


# Suma de las Diagonales

In [43]:
import numpy as np
a = np.array([[2, 2, 1],
               [1, 3, 1],
               [1, 2, 2]])
print("a = ")
print(a)
print("\nTrace:", a.trace())
print("Trace:", sum(a.diagonal()))

a = 
[[2 2 1]
 [1 3 1]
 [1 2 2]]

Trace: 7
Trace: 7


# Rango

In [44]:
a = np.arange(1, 10)
a.shape = (3, 3)
print("a = ")
print(a)
rank = np.linalg.matrix_rank(a)
print("\nRank:", rank)

a = 
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Rank: 2


# Verdadera Inversa

In [45]:
a = np.array([[2, 2, 1],
               [1, 3, 1],
               [1, 2, 2]])
print("a = ")
print(a)
det = np.linalg.det(a)
print("\nDeterminant round:", np.round(det))
print("\nDeterminant No-round:", det)
inv = np.linalg.inv(a)
print("\nInverse of a = ")
print(inv)

a = 
[[2 2 1]
 [1 3 1]
 [1 2 2]]

Determinant round: 5.0

Determinant No-round: 4.999999999999999

Inverse of a = 
[[ 0.8 -0.4 -0.2]
 [-0.2  0.6 -0.2]
 [-0.2 -0.4  0.8]]


# Flatten:

In [46]:
#Es un método para colocar en secuencia (vector fila) todos los elementos de un matriz rectangular.

In [47]:
a = np.arange(1, 10)
a.shape = (3, 3)
print("a = ")
print(a)
print("\nAfter flattening")
print("------------------")
print(a.flatten())

a = 
[[1 2 3]
 [4 5 6]
 [7 8 9]]

After flattening
------------------
[1 2 3 4 5 6 7 8 9]


# Eigenvalues and eigenvectors

In [48]:
a = np.array([[2, 2, 1],
               [1, 3, 1],
               [1, 2, 2]])
print("a = ")
print(a)
w, v = np.linalg.eig(a)
print("\nEigenvalues:")
print(w)
print("\nEigenvectors:")
print(v)

a = 
[[2 2 1]
 [1 3 1]
 [1 2 2]]

Eigenvalues:
[5. 1. 1.]

Eigenvectors:
[[ 0.57735027  0.90453403  0.36601928]
 [ 0.57735027 -0.30151134 -0.55609927]
 [ 0.57735027 -0.30151134  0.74617926]]
